spring.datasource.url=jdbc:h2:mem:stripe_demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.application.name=stripe-payment
spring.jpa.show-sql=false

stripe.secretKey=${STRIPE_SECRET_KEY:}
stripe.webhookSecret=${STRIPE_WEBHOOK_SECRET:}
app.base-url=${APP_BASE_URL:http://ec2-98-84-17-175.compute-1.amazonaws.com}

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=stripe-payment-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s

app.kafka.enabled=true
app.kafka.topics.order-events=order-events
app.kafka.topics.payment-events=payment-events
app.redis.enabled=true
app.redis.payment-idempotency-ttl-minutes=30
app.redis.cancel-lock-ttl-seconds=120
app.redis.webhook-lock-ttl-minutes=30
app.redis.notification-lock-ttl-minutes=1440
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.producer.properties.max.block.ms=1000

app.mail.enabled=${APP_MAIL_ENABLED:false}
app.mail.from=${MAIL_FROM:no-reply@checkoutstudio.local}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}
